version: '3'

services:
  payload:
    build: .
    environment:
      - PAYLOAD_SECRET=FOR_TESTING_ONLY
    ports:
      - 3000:3000
    volumes:
      - db:/app/db
      - uploads:/app/uploads

volumes:
  db:
  uploads: